package POJO;
// Generated 07-feb-2017 13:28:55 by Hibernate Tools 4.3.1



/**
 * Reloj generated by hbm2java
 */
public class Reloj  implements java.io.Serializable {


     private Integer id;
     private String marca;
     private int votos;
     private byte[] icono;

    public Reloj() {
    }

    public Reloj(String id){
        Integer intObj = new Integer(Integer.parseInt(id));
        this.id = intObj;
    }
    
    public Reloj(String marca, int votos, byte[] icono) {
       this.marca = marca;
       this.votos = votos;
       this.icono = icono;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getVotos() {
        return this.votos;
    }
    
    public void setVotos(int votos) {
        this.votos = votos;
    }
    public byte[] getIcono() {
        return this.icono;
    }
    
    public void setIcono(byte[] icono) {
        this.icono = icono;
    }


    @Override
    public String toString() {
        return "Reloj: " + "marca=" + marca + ", votos=" + votos + ", icono=" + icono;
    }

}


